/* eslint-disable react/no-unknown-property */
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// author: Agustín Hönnun (https://sketchfab.com/Agustin_Honnun)
// license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// source: https://sketchfab.com/3d-models/stylized-rock-agustin-honnun-ae21c3d47cb14323a3bb06ccb562e368
// title: Stylized Rock | Agustin Hönnun
// */

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Stone_low_Stone_MAT_0: THREE.Mesh;
  };
  materials: {
    Stone_MAT: THREE.MeshStandardMaterial;
  };
};

export function Rocks1(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/stylized_rock__agustin_honnun.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Stone_low_Stone_MAT_0.geometry}
              material={materials.Stone_MAT}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/stylized_rock__agustin_honnun.glb");
