/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cylinder011: THREE.Mesh;
    Cylinder011_1: THREE.Mesh;
    Cylinder017: THREE.Mesh;
    Cylinder017_1: THREE.Mesh;
  };
  materials: {
    Stem_Material: THREE.MeshStandardMaterial;
    LeafMateria: THREE.MeshStandardMaterial;
  };
};

export function Palms(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/PalmPair.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Stem_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011_1.geometry}
        material={materials.LeafMateria}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017.geometry}
        material={materials.Stem_Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder017_1.geometry}
        material={materials.LeafMateria}
      />
    </group>
  );
}

useGLTF.preload("/PalmPair.glb");
